resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-local-recipe.yml@templates
  parameters:
    package: cmake
    package_version: 3.28.1
    destination_repository: ccdc-3rdparty-conan
    macos_deployment_target: 10.14
    build_types:
      - Release
    platforms:
      - centos7_gcc10
      - ubuntu2004_gcc10
      - macos11_xcode12
      - macos12_xcode13
      - win2019_vs2019
